Update build-distribute.yml

diff --git a/.github/workflows/build-distribute.yml b/.github/workflows/build-distribute.yml
--- a/.github/workflows/build-distribute.yml
+++ b/.github/workflows/build-distribute.yml
@@ -61,6 +61,22 @@ jobs:
       - name: Create local.properties
         run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
 
+      - name: Get version from build.gradle 
+        id: get-version 
+        run: | 
+          VERSION_NAME=$(grep 'versionName' app/build.gradle | sed -E "s/.*versionName ['\"]([0-9.]+)['\"].*/\1/") 
+          echo "version=$VERSION_NAME" >> $GITHUB_ENV 
+        env: 
+          GITHUB_ENV: $GITHUB_ENV
+
+      - name: Verify version 
+        run: | 
+          if [ -z "$VERSION_NAME" ]; then 
+            echo "Version name could not be extracted. Exiting." exit 1 
+          else 
+            echo "Version name is $VERSION_NAME" 
+          fi
+
       - name: Build and Distribute app to Firebase
         id: build-and-distribute
         run: |
